require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/tasks/*'
