sudo: false
cache: bundler
language: ruby
matrix:
  include:
    - rvm: jruby-9.0.1.0
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.4.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --remote bundler
script:
  - bundle exec rake ci
